[README] 'pgsql' should be 'psql'
Using of `pgsql` causing error as it's wrong, eg:

```
cf conduit postgres-instance -- pgsql < mybackup.sql

OK Waiting for conduit app to become available
OK Starting port forwarding
OK Waiting for port forwarding
OK Preparing command: [pgsql]
Error: cannot find 'pgsql' in PATH
```

It should be `psql`.